### ISSUE TITLE
An error occurred when the convertTo is called

### ISSUE THREAD

**Issue by zhxxhit** [mcamplan/DSKCF_CPP#2]
const DepthHistogram DepthHistogram::createHistogram( const uint step, const cv::Mat & region, const cv::Mat1b & mask )
{
  cv::Mat1f region32f;  //cv::Mat3f region32f;
  DepthHistogram result;
  int histogramBinCount = 0;
  region.convertTo( region32f, CV_32F );
  cv::minMaxLoc( region32f, &result.m_minimum, &result.m_maximum, nullptr, nullptr, mask );
........................
}

I modify the “region32f” of type Mat3f，the error is gone . When "minMaxLoc" called error again

Error：【
The inferior stopped because it received a signal from the operating system.
Signal name : 
SIGABRT
Signal meaning : 
Aborted
】

my command line arguments（using Princeton’s validation dataset "bear_front"）:
【--depth --depth_image_name_expansion /dskcf%05d.png --depth_sequence xzx/bear_front_byconvert/depth --image_name_expansion /dskcf%05d.png --seq xzx/bear_front_byconvert/rgb 】

**Comment by 8greg8** [comment]
I had the same problem when using OpenCV-3.2.0. When I downgraded to OpenCV-3.0.0 everything worked. @zhxxhit check your OpenCV version.

**Comment by zhxxhit** [comment]
@8greg8 My Opencv is 3.0.0

**Comment by jh14778** [comment]
So the problem here may be an interaction between the OpenCV version and the FFmpeg version.

What can happen is that the depth images are converted to a gray-scale RGB image, thus having three channels and 8-bit depth.

The function `DepthHistogram::createHistogram` assumes that `region` is a non-empty one channel 16-bit image.

Although I can only speculate exactly what the error you're experiencing is, these two facts could explain it.

I will take a closer look this evening, but it may be out of the scope of this project.

**Comment by zhxxhit** [comment]
@jh14778 thank you very much for your analysis of the problem. I'm not familiar with the interaction  problem between the OpenCV version and the FFmpeg version.I solved my problem by changing the code of opencv3.0.0(stat.cpp & matrix.cpp).

void _OutputArray::create(Size _sz, int mtype, int i, bool allowTransposed, int fixedDepthMask) const
{
    int k = kind();
    if( k == MAT && i < 0 && !allowTransposed && fixedDepthMask == 0 )
    {
        CV_Assert(!fixedSize() || ((Mat*)obj)->size.operator()() == _sz);
        //CV_Assert(!fixedType() || ((Mat*)obj)->type() == mtype);
        ((Mat*)obj)->create(_sz, mtype);
        return;
    }....

void cv::minMaxIdx(InputArray _src, double* minVal,
                   double* maxVal, int* minIdx, int* maxIdx,
                   InputArray _mask)
{
    int type = _src.type(), depth = CV_MAT_DEPTH(type), cn = CV_MAT_CN(type);
    //CV_Assert( (cn == 1 && (_mask.empty() || _mask.type() == CV_8U)) ||
        //(cn > 1 && _mask.empty() && !minIdx && !maxIdx) );
.......

**Comment by jh14778** [comment]
@zhxxhit I'm not sure that those changes to OpenCV will have the desired result.
Those CV_Assert statements represent the function's preconditions and shouldn't be changed lightly.
For example, the documentation for [`cv::minMaxIdx`](http://docs.opencv.org/3.0-beta/modules/core/doc/operations_on_arrays.html#minmaxidx) states: 
> The function does not work with multi-channel arrays.

I am also unsure why you want to change the type of `region32f` from `cv::Mat1f` to `cv::Mat3f` because it represents a depth map, which only has one channel (the depth of the pixel).

Any clarrification on this would help me and @mcamplan understand, if this is a bug or not.

**Comment by yycho0108** [comment]
For those of you who are wondering, the depth map is loaded from the .png file so it has three channels, which is why the code will complain. Simply convert it to grayscale inside TrackerRun::update() like:
if( _paras.useDepth )
	{
		Mat dummy;
		_cap[ 1 ] >> dummy;//_image[ 1 ];
		cv::cvtColor(dummy, _image[1], cv::COLOR_RGB2GRAY);
	}
